development:
 database: project_blog
 adapter: postgresql
 username: postgres
 password: 12345678
 host: localhost
 pool: 5
 timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
  username: postgres
  password: 12345678